# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2647aff737cafe556d6b4b8634b5506c3e2c0aeb6934be8330265f3aa13a012979e83ad658e78197465b1e29c4e9aa273b660c15b3c841e570a7fd13d06e5903

test:
  secret_key_base: 685caa54e7e5656e9cb369a9a74b7691c1e410288767724c05156d65dfff4b3d170aa78323b49bae69eb57af2db8c3ca9baa9dcf79fb25911fa349a02214fc4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
